### ISSUE TITLE
Is create error

### ISSUE THREAD

**Issue by imjack** [TheSolidCrafter/ASkyBlock-Nukkit#34] opened 2017-10-15 19:40 UTC
Hello Larry, 

If possible could you give me some method(skype/discord etc) of contact to speak to you privately I am very interested in this project.

### Issue Description
Write a short description about the issue
/is create causes some sort of gson stackoverflow 

### Steps to Reproduce the Issue

1. ... run the plugin fresh and do /is create

### OS and Versions

* ASkyBlock version: 0.3.7-BETA

* Nukkit Version:  v1.2.2 (protocol version 137)

* Java Version:  8 
* Win 10

### Crashdump, Backtrace or Other Files

```
<!--- Copy and paste your backtrace here... -->
```
https://pastebin.com/hi32npaR

**Comment by larryTheCoder** [comment] 2017-10-22 04:39
Full stack trace please.
Discord: MrPotato101#0060

**Comment by imjack** [comment] 2017-10-22 18:51
That is the full stack trace.

**Comment by larryTheCoder** [comment] 2017-10-24 02:18
confirmed.

**Comment by larryTheCoder** [comment] 2017-11-03 05:59
@imjack this problem is fixed in next commit. Because i want to test if all of it had been fixed

**Comment by imjack** [comment] 2017-11-16 20:52
I'll have a test now, Also i can't seem to find you on discord.

**Comment by larryTheCoder** [comment] 2018-04-10 12:05
The problem fixed in current commit.

**Closed by larryTheCoder** 2018-04-10 12:06 UTC
